export const CANVAS = document.getElementById('gameCanvas');
export const CTX = CANVAS.getContext('2d');
export const DEBUG_HUD = document.getElementById('debugHUD');
export const TILE_SIZE = 40;
export const GRAVITY = 0.6;
export const FRICTION = 0.85;
export const ACCELERATION = 0.8;
export const JUMP_FORCE = -13;
export const TERMINAL_VELOCITY = 15;
export const LEVEL_WIDTH = 400; // This might need to be mutable if it changes per level, but currently it's a const default
export const LEVEL_HEIGHT = 60;
export const FPS = 60;
export const INTERVAL = 1000 / FPS;

export const ASSETS = {
    dirtBase: "#5d4037", dirtLight: "#8d6e63", grassTop: "#4caf50",
    stoneBase: "#546e7a", stoneLight: "#78909c",
    skyTop: "#1e3c72", skyBot: "#2a5298",
    checkpoint: "#00ff41", leash: "#555", tank: "#e74c3c", ladder: "#d35400"
};

export const CHARACTERS = [
    { id: 'pug', name: 'IRON MUTT', type: 'dog_flat', cSkin: '#f3cf98', cDark: '#3b302a', cSuit: '#b0c4de', pType: 'laser', pColor: '#a020f0' },
    { id: 'raccoon', name: 'CPT TRASH', type: 'raccoon', cSkin: '#888', cDark: '#444', cSuit: '#555', pType: 'boomerang', pColor: '#aaa' },
    { id: 'cat', name: 'BAT CAT', type: 'cat', cSkin: '#222', cDark: '#000', cSuit: '#111', pType: 'boomerang', pColor: '#ff69b4', trait: 'climb' },
    { id: 'corgi', name: 'THOR-GI', type: 'dog_pointy', cSkin: '#E3C099', cDark: '#FFF', cSuit: '#333', pType: 'boomerang', pColor: '#00FFFF' },
    { id: 'hulk', name: 'HULK-POODLE', type: 'poodle', cSkin: '#00FF00', cDark: '#006400', cSuit: '#800080', pType: 'melee_smash', pColor: '#00FF00' },
    { id: 'spider', name: 'SPIDER-PIG', type: 'pig', cSkin: '#FFC0CB', cDark: '#FF69B4', cSuit: '#FF0000', pType: 'gun', pColor: '#FFF', trait: 'climb' },
    { id: 'wolvie', name: 'WOLVER-WEENIE', type: 'dog_long', cSkin: '#8B4513', cDark: '#000', cSuit: '#FFFF00', pType: 'melee_slash', pColor: '#C0C0C0' },
    { id: 'dead', name: 'DEAD-POODLE', type: 'poodle', cSkin: '#FF0000', cDark: '#000', cSuit: '#333', pType: 'gun', pColor: '#FF0000' },
    { id: 'cap', name: 'CAPTAIN EAGLE', type: 'bird', cSkin: '#FFF', cDark: '#A52A2A', cSuit: '#0000FF', pType: 'boomerang', pColor: '#FFF', trait: 'fly' },
    { id: 'ironmouse', name: 'IRON-MOUSE', type: 'rodent', cSkin: '#808080', cDark: '#404040', cSuit: '#FF0000', pType: 'laser', pColor: '#FFFF00', trait: 'fly' },
    { id: 'widow', name: 'BLACK WIDOW-PUG', type: 'dog_flat', cSkin: '#000', cDark: '#111', cSuit: '#222', pType: 'gun', pColor: '#00FFFF', trait: 'climb' },
    { id: 'hawkeye', name: 'HAWK-HEDGEHOG', type: 'hedgehog', cSkin: '#D2B48C', cDark: '#8B4513', cSuit: '#800080', pType: 'grenade', pColor: '#DDD' },
    { id: 'strange', name: 'DR STRANGE-CAT', type: 'cat', cSkin: '#444', cDark: '#222', cSuit: '#0000FF', pType: 'magic', pColor: '#FFA500' },
    { id: 'panther', name: 'BLACK PANTHER', type: 'cat', cSkin: '#111', cDark: '#000', cSuit: '#222', pType: 'melee_slash', pColor: '#800080', trait: 'climb' },
    { id: 'ant', name: 'ANT-EATER-MAN', type: 'anteater', cSkin: '#808080', cDark: '#404040', cSuit: '#FF0000', pType: 'melee_smash', pColor: '#FF0000', trait: 'climb' },
    { id: 'starlord', name: 'STAR-LORD-FOX', type: 'fox', cSkin: '#FF8C00', cDark: '#8B0000', cSuit: '#8B4513', pType: 'laser', pColor: '#FFFF00', trait: 'fly' },
    { id: 'gamora', name: 'GAMORA-GECKO', type: 'lizard', cSkin: '#00FF00', cDark: '#006400', cSuit: '#000', pType: 'melee_slash', pColor: '#00FF00', trait: 'climb' },
    { id: 'drax', name: 'DRAX-BULLDOG', type: 'dog_flat', cSkin: '#008000', cDark: '#FF0000', cSuit: '#000080', pType: 'melee_slash', pColor: '#CCC' },
    { id: 'groot', name: 'GROOT-BARK', type: 'tree', cSkin: '#8B4513', cDark: '#A0522D', cSuit: '#654321', pType: 'melee_smash', pColor: '#8B4513' },
    { id: 'rocket', name: 'ROCKET-RABBIT', type: 'rabbit', cSkin: '#A9A9A9', cDark: '#696969', cSuit: '#FF4500', pType: 'grenade', pColor: '#FF4500', trait: 'fly' },
    { id: 'vision', name: 'VISION-ZEBRA', type: 'horse', cSkin: '#FFC0CB', cDark: '#008000', cSuit: '#FFFF00', pType: 'laser', pColor: '#FFFF00', trait: 'fly' },
    { id: 'scarlet', name: 'SCARLET-SKUNK', type: 'skunk', cSkin: '#000', cDark: '#FFF', cSuit: '#FF0000', pType: 'magic', pColor: '#FF0000' },
    { id: 'quick', name: 'QUICK-CHEETAH', type: 'cat', cSkin: '#D3D3D3', cDark: '#A9A9A9', cSuit: '#87CEEB', pType: 'melee_slash', pColor: '#87CEEB' },
    { id: 'winter', name: 'WINTER-WOLF', type: 'dog_pointy', cSkin: '#FFF', cDark: '#808080', cSuit: '#000', pType: 'gun', pColor: '#C0C0C0' },
    { id: 'falcon', name: 'FALCON-PIGEON', type: 'bird', cSkin: '#808080', cDark: '#696969', cSuit: '#FF0000', pType: 'gun', pColor: '#CCC', trait: 'fly' },
    { id: 'war', name: 'WAR-RHINO', type: 'rhino', cSkin: '#708090', cDark: '#2F4F4F', cSuit: '#000', pType: 'grenade', pColor: '#999' },
    { id: 'dare', name: 'DAREDEVIL-DOG', type: 'dog_pointy', cSkin: '#B22222', cDark: '#800000', cSuit: '#FF0000', pType: 'melee_slash', pColor: '#FF0000' },
    { id: 'punish', name: 'PUNISHER-PENGUIN', type: 'bird', cSkin: '#000', cDark: '#FFF', cSuit: '#000', pType: 'spread', pColor: '#FFF' },
    { id: 'shang', name: 'SHANG-CHI-PANDA', type: 'bear', cSkin: '#000', cDark: '#FFF', cSuit: '#FF0000', pType: 'melee_smash', pColor: '#FFD700' },
    { id: 'eternal', name: 'ETERNAL-ELEPHANT', type: 'elephant', cSkin: '#808080', cDark: '#696969', cSuit: '#FFD700', pType: 'magic', pColor: '#FFD700' },
    { id: 'moon', name: 'MOON-OWL', type: 'bird', cSkin: '#FFF', cDark: '#EEE', cSuit: '#DDD', pType: 'boomerang', pColor: '#FFF', trait: 'fly' },
    { id: 'shehulk', name: 'SHE-HULK-HAMSTER', type: 'rodent', cSkin: '#32CD32', cDark: '#006400', cSuit: '#800080', pType: 'melee_smash', pColor: '#00FF00' },
    { id: 'ghost', name: 'GHOST-GOAT', type: 'goat', cSkin: '#FFF', cDark: '#FF4500', cSuit: '#000', pType: 'melee_slash', pColor: '#FF4500' },
    { id: 'unicorncyborg', name: 'UNICORN-CYBORG', type: 'robot', cSkin: '#6495ED', cDark: '#FFEBCD', cSuit: '#2E8B57', pType: 'lightning', pColor: '#FFE4C4' },
    { id: 'creaturehedgehog', name: 'CREATURE-HEDGEHOG', type: 'hedgehog', cSkin: '#00FF00', cDark: '#DAA520', cSuit: '#008B8B', pType: 'melee_smash', pColor: '#40E0D0' },
    { id: 'storestump', name: 'STORE-STUMP', type: 'tree', cSkin: '#006400', cDark: '#6495ED', cSuit: '#000000', pType: 'boomerang', pColor: '#FFDEAD' },
    { id: 'galaxygod', name: 'GALAXY-GOD', type: 'human', cSkin: '#F0F8FF', cDark: '#BDB76B', cSuit: '#DAA520', pType: 'shuriken', pColor: '#FAF0E6', trait: 'fly' },
    { id: 'wraithhouse', name: 'WRAITH-HOUSE', type: 'stone', cSkin: '#800000', cDark: '#98FB98', cSuit: '#000080', pType: 'acid_spit', pColor: '#5F9EA0' },
    { id: 'ninjakangaroo', name: 'NINJA-KANGAROO', type: 'rabbit', cSkin: '#DCDCDC', cDark: '#F0FFF0', cSuit: '#8FBC8F', pType: 'card_throw', pColor: '#808080', trait: 'climb' },
    { id: 'devilcastle', name: 'DEVIL-CASTLE', type: 'stone', cSkin: '#48D1CC', cDark: '#008000', cSuit: '#0000FF', pType: 'water_gun', pColor: '#7CFC00' },
    { id: 'aquaalpaca', name: 'AQUA-ALPACA', type: 'horse', cSkin: '#FFE4E1', cDark: '#FFDEAD', cSuit: '#F5DEB3', pType: 'rocket', pColor: '#FAFAD2' },
    { id: 'makeupgate', name: 'MAKEUP-GATE', type: 'stone', cSkin: '#FFDEAD', cDark: '#F0F8FF', cSuit: '#D2B48C', pType: 'fireball', pColor: '#008000' },
    { id: 'alienboulder', name: 'ALIEN-BOULDER', type: 'stone', cSkin: '#808080', cDark: '#FAEBD7', cSuit: '#006400', pType: 'ice_beam', pColor: '#00BFFF' },
    { id: 'skeletonram', name: 'SKELETON-RAM', type: 'goat', cSkin: '#006400', cDark: '#800080', cSuit: '#00FA9A', pType: 'gun', pColor: '#B0C4DE' },
    { id: 'aquariumforest', name: 'AQUARIUM-FOREST', type: 'tree', cSkin: '#FFFAFA', cDark: '#1E90FF', cSuit: '#556B2F', pType: 'laser', pColor: '#F5F5DC' },
    { id: 'darklog', name: 'DARK-LOG', type: 'tree', cSkin: '#F0E68C', cDark: '#00FFFF', cSuit: '#00CED1', pType: 'water_gun', pColor: '#FFFFFF' },
    { id: 'factoryskeleton', name: 'FACTORY-SKELETON', type: 'skeleton', cSkin: '#FDF5E6', cDark: '#FFFACD', cSuit: '#556B2F', pType: 'acid_spit', pColor: '#F5F5F5' },
    { id: 'defenderroof', name: 'DEFENDER-ROOF', type: 'stone', cSkin: '#A52A2A', cDark: '#0000FF', cSuit: '#000000', pType: 'boomerang', pColor: '#D2691E' },
    { id: 'robbereagle', name: 'ROBBER-EAGLE', type: 'bird', cSkin: '#F8F8FF', cDark: '#4682B4', cSuit: '#3CB371', pType: 'lightning', pColor: '#20B2AA', trait: 'fly' },
    { id: 'professorskunk', name: 'PROFESSOR-SKUNK', type: 'skunk', cSkin: '#F4A460', cDark: '#800000', cSuit: '#2F4F4F', pType: 'rocket', pColor: '#800000' },
    { id: 'earthbuffalo', name: 'EARTH-BUFFALO', type: 'cow', cSkin: '#7FFF00', cDark: '#4169E1', cSuit: '#FFFF00', pType: 'fireball', pColor: '#00FFFF' },
    { id: 'ogreguinea', name: 'OGRE-GUINEA', type: 'rodent', cSkin: '#FFE4C4', cDark: '#708090', cSuit: '#2F4F4F', pType: 'gun', pColor: '#00CED1' },
    { id: 'artistalien', name: 'ARTIST-ALIEN', type: 'alien', cSkin: '#FFEBCD', cDark: '#ADFF2F', cSuit: '#0000CD', pType: 'ice_beam', pColor: '#F5F5F5' },
    { id: 'firedonkey', name: 'FIRE-DONKEY', type: 'horse', cSkin: '#191970', cDark: '#800000', cSuit: '#2F4F4F', pType: 'water_gun', pColor: '#EEE8AA' },
    { id: 'fighterhawk', name: 'FIGHTER-HAWK', type: 'bird', cSkin: '#F8F8FF', cDark: '#006400', cSuit: '#F0E68C', pType: 'gun', pColor: '#F0FFFF', trait: 'fly' },
    { id: 'trollpeacock', name: 'TROLL-PEACOCK', type: 'bird', cSkin: '#8FBC8F', cDark: '#40E0D0', cSuit: '#00FF7F', pType: 'gun', pColor: '#FFF5EE', trait: 'fly' },
    { id: 'detectivemonkey', name: 'DETECTIVE-MONKEY', type: 'monkey', cSkin: '#000080', cDark: '#F5F5F5', cSuit: '#F0FFFF', pType: 'laser', pColor: '#FAEBD7', trait: 'climb' },
    { id: 'homelizard', name: 'HOME-LIZARD', type: 'lizard', cSkin: '#808000', cDark: '#CD853F', cSuit: '#BC8F8F', pType: 'melee_slash', pColor: '#FFF8DC', trait: 'climb' },
    { id: 'headsmanshark', name: 'HEADSMAN-SHARK', type: 'fish', cSkin: '#4682B4', cDark: '#00FF7F', cSuit: '#FFE4C4', pType: 'melee_slash', pColor: '#D3D3D3' },
    { id: 'caferaven', name: 'CAFE-RAVEN', type: 'bird', cSkin: '#008B8B', cDark: '#90EE90', cSuit: '#90EE90', pType: 'rocket', pColor: '#FFA500', trait: 'fly' },
    { id: 'phoenixdemon', name: 'PHOENIX-DEMON', type: 'goat', cSkin: '#EEE8AA', cDark: '#7FFF00', cSuit: '#6B8E23', pType: 'grenade', pColor: '#FFE4C4', trait: 'fly' },
    { id: 'alienlion', name: 'ALIEN-LION', type: 'cat', cSkin: '#87CEFA', cDark: '#008B8B', cSuit: '#708090', pType: 'melee_slash', pColor: '#00FF00' },
    { id: 'paintervillain', name: 'PAINTER-VILLAIN', type: 'human', cSkin: '#F0E68C', cDark: '#3CB371', cSuit: '#66CDAA', pType: 'laser', pColor: '#F0F8FF' },
    { id: 'mageslime', name: 'MAGE-SLIME', type: 'alien', cSkin: '#00FA9A', cDark: '#BDB76B', cSuit: '#8FBC8F', pType: 'melee_smash', pColor: '#008080' },
    { id: 'journalistceiling', name: 'JOURNALIST-CEILING', type: 'stone', cSkin: '#FFDAB9', cDark: '#A0522D', cSuit: '#228B22', pType: 'melee_slash', pColor: '#800000' },
    { id: 'bakerhamster', name: 'BAKER-HAMSTER', type: 'rodent', cSkin: '#808000', cDark: '#00FFFF', cSuit: '#2E8B57', pType: 'fireball', pColor: '#87CEEB' },
    { id: 'zombiefish', name: 'ZOMBIE-FISH', type: 'fish', cSkin: '#F0F8FF', cDark: '#D2691E', cSuit: '#008000', pType: 'ice_beam', pColor: '#F0FFFF' },
    { id: 'chefdeer', name: 'CHEF-DEER', type: 'goat', cSkin: '#800000', cDark: '#EEE8AA', cSuit: '#FFE4C4', pType: 'rocket', pColor: '#000080' },
    { id: 'resortstone', name: 'RESORT-STONE', type: 'stone', cSkin: '#808080', cDark: '#FAFAD2', cSuit: '#8FBC8F', pType: 'boomerang', pColor: '#00FF7F' },
    { id: 'hospitalchipmunk', name: 'HOSPITAL-CHIPMUNK', type: 'rodent', cSkin: '#FFEFD5', cDark: '#FFFACD', cSuit: '#008B8B', pType: 'card_throw', pColor: '#5F9EA0', trait: 'climb' },
    { id: 'mutantkoala', name: 'MUTANT-KOALA', type: 'bear', cSkin: '#4682B4', cDark: '#DCDCDC', cSuit: '#008000', pType: 'laser', pColor: '#696969', trait: 'climb' },
    { id: 'directordirt', name: 'DIRECTOR-DIRT', type: 'stone', cSkin: '#00FA9A', cDark: '#F5FFFA', cSuit: '#FFFAFA', pType: 'spread', pColor: '#008080' },
    { id: 'spectrebison', name: 'SPECTRE-BISON', type: 'cow', cSkin: '#FFF0F5', cDark: '#FFFFF0', cSuit: '#9ACD32', pType: 'card_throw', pColor: '#FFDEAD' },
    { id: 'convictchicken', name: 'CONVICT-CHICKEN', type: 'duck', cSkin: '#D2691E', cDark: '#FFEBCD', cSuit: '#808080', pType: 'grenade', pColor: '#FFFF00', trait: 'fly' },
    { id: 'innmud', name: 'INN-MUD', type: 'stone', cSkin: '#FAF0E6', cDark: '#008080', cSuit: '#C0C0C0', pType: 'card_throw', pColor: '#9ACD32' },
    { id: 'killerdonkey', name: 'KILLER-DONKEY', type: 'horse', cSkin: '#7FFF00', cDark: '#F0FFFF', cSuit: '#FFFACD', pType: 'grenade', pColor: '#708090' },
    { id: 'professorkangaroo', name: 'PROFESSOR-KANGAROO', type: 'rabbit', cSkin: '#FFE4C4', cDark: '#C0C0C0', cSuit: '#000000', pType: 'spread', pColor: '#40E0D0' },
    { id: 'paramedicpeacock', name: 'PARAMEDIC-PEACOCK', type: 'bird', cSkin: '#00FF00', cDark: '#FFF0F5', cSuit: '#0000FF', pType: 'laser', pColor: '#FDF5E6', trait: 'fly' },
    { id: 'restaurantwolf', name: 'RESTAURANT-WOLF', type: 'wolf', cSkin: '#191970', cDark: '#FFE4C4', cSuit: '#B8860B', pType: 'ice_beam', pColor: '#E6E6FA' },
    { id: 'knightsheep', name: 'KNIGHT-SHEEP', type: 'goat', cSkin: '#D2691E', cDark: '#B8860B', cSuit: '#F0FFF0', pType: 'acid_spit', pColor: '#000080' },
    { id: 'ranchwombat', name: 'RANCH-WOMBAT', type: 'rodent', cSkin: '#708090', cDark: '#D3D3D3', cSuit: '#000080', pType: 'melee_slash', pColor: '#FFE4C4', trait: 'climb' },
    { id: 'murdererforest', name: 'MURDERER-FOREST', type: 'tree', cSkin: '#006400', cDark: '#F8F8FF', cSuit: '#4682B4', pType: 'spread', pColor: '#008B8B' },
    { id: 'nightllama', name: 'NIGHT-LLAMA', type: 'horse', cSkin: '#808000', cDark: '#008000', cSuit: '#FFFF00', pType: 'melee_smash', pColor: '#FFFF00' },
    { id: 'musicianturkey', name: 'MUSICIAN-TURKEY', type: 'duck', cSkin: '#228B22', cDark: '#DEB887', cSuit: '#FFFAF0', pType: 'spread', pColor: '#FF0000', trait: 'fly' },
    { id: 'oozecrow', name: 'OOZE-CROW', type: 'bird', cSkin: '#ADD8E6', cDark: '#228B22', cSuit: '#778899', pType: 'lightning', pColor: '#9ACD32', trait: 'fly' },
    { id: 'lordblob', name: 'LORD-BLOB', type: 'alien', cSkin: '#008B8B', cDark: '#F8F8FF', cSuit: '#F0E68C', pType: 'water_gun', pColor: '#800080' },
    { id: 'shadowpanda', name: 'SHADOW-PANDA', type: 'bear', cSkin: '#6495ED', cDark: '#008080', cSuit: '#808080', pType: 'melee_smash', pColor: '#F0F8FF' },
    { id: 'spyboulder', name: 'SPY-BOULDER', type: 'stone', cSkin: '#7FFFD4', cDark: '#ADD8E6', cSuit: '#E6E6FA', pType: 'card_throw', pColor: '#98FB98' },
    { id: 'stylistearth', name: 'STYLIST-EARTH', type: 'stone', cSkin: '#006400', cDark: '#F0E68C', cSuit: '#00CED1', pType: 'card_throw', pColor: '#90EE90' },
    { id: 'sparock', name: 'SPA-ROCK', type: 'stone', cSkin: '#000000', cDark: '#DEB887', cSuit: '#000080', pType: 'lightning', pColor: '#0000FF' },
    { id: 'farmpig', name: 'FARM-PIG', type: 'pig', cSkin: '#696969', cDark: '#696969', cSuit: '#FFF5EE', pType: 'lightning', pColor: '#00FFFF' },
    { id: 'guardbrick', name: 'GUARD-BRICK', type: 'stone', cSkin: '#66CDAA', cDark: '#C0C0C0', cSuit: '#40E0D0', pType: 'shuriken', pColor: '#008B8B' },
    { id: 'sunpegasus', name: 'SUN-PEGASUS', type: 'horse', cSkin: '#BDB76B', cDark: '#FFFAFA', cSuit: '#008000', pType: 'lightning', pColor: '#0000CD', trait: 'fly' },
    { id: 'shopstone', name: 'SHOP-STONE', type: 'stone', cSkin: '#F0FFFF', cDark: '#A0522D', cSuit: '#FFEFD5', pType: 'fireball', pColor: '#E6E6FA' },
    { id: 'princemonster', name: 'PRINCE-MONSTER', type: 'alien', cSkin: '#000080', cDark: '#808000', cSuit: '#FFDEAD', pType: 'gun', pColor: '#FFDEAD' },
    { id: 'directorreindeer', name: 'DIRECTOR-REINDEER', type: 'goat', cSkin: '#8FBC8F', cDark: '#A52A2A', cSuit: '#00FA9A', pType: 'gun', pColor: '#B0C4DE', trait: 'fly' },
    { id: 'policecroc', name: 'POLICE-CROC', type: 'croc', cSkin: '#228B22', cDark: '#006400', cSuit: '#A52A2A', pType: 'shuriken', pColor: '#A0522D' },
    { id: 'composerfrog', name: 'COMPOSER-FROG', type: 'frog', cSkin: '#32CD32', cDark: '#006400', cSuit: '#9ACD32', pType: 'boomerang', pColor: '#FFDEAD' },
    { id: 'nunturtle', name: 'NUN-TURTLE', type: 'turtle', cSkin: '#2E8B57', cDark: '#006400', cSuit: '#FFFAFA', pType: 'melee_slash', pColor: '#FFE4E1' },
    { id: 'homepumpkin', name: 'HOME-PUMPKIN', type: 'pumpkin', cSkin: '#FFA500', cDark: '#006400', cSuit: '#D3D3D3', pType: 'ice_beam', pColor: '#ADFF2F' },
];
