export const CANVAS = document.getElementById('gameCanvas');
export const CTX = CANVAS.getContext('2d');
export const DEBUG_HUD = document.getElementById('debugHUD');
export const TILE_SIZE = 40;
export const GRAVITY = 0.6;
export const FRICTION = 0.85;
export const ACCELERATION = 0.8;
export const JUMP_FORCE = -13;
export const TERMINAL_VELOCITY = 15;
export const LEVEL_WIDTH = 400; // This might need to be mutable if it changes per level, but currently it's a const default
export const LEVEL_HEIGHT = 60;
export const FPS = 60;
export const INTERVAL = 1000 / FPS;

export const ASSETS = {
    dirtBase: "#5d4037", dirtLight: "#8d6e63", grassTop: "#4caf50",
    stoneBase: "#546e7a", stoneLight: "#78909c",
    skyTop: "#1e3c72", skyBot: "#2a5298",
    checkpoint: "#00ff41", leash: "#555", tank: "#e74c3c", ladder: "#d35400"
};

export const CHARACTERS = [

    { id: 'willywombat', name: 'WILLY WOMBAT', type: 'rodent', cSkin: '#deb887', cDark: '#800080', cSuit: '#800080', pType: 'cane_candy', pColor: '#dda0dd' },
    { id: 'mandalmatian', name: 'MAN-DALMATIAN', type: 'dog_pointy', cSkin: '#fff', cDark: '#000', cSuit: '#c0c0c0', pType: 'flamethrower', pColor: '#ff4500', trait: 'fly' },
    { id: 'earthbuffalo', name: 'EARTH-BUFFALO', type: 'cow', cSkin: '#7FFF00', cDark: '#4169E1', cSuit: '#FFFF00', pType: 'fireball', pColor: '#00FFFF' },
    { id: 'kungfupanther', name: 'KUNG FU PANTHER', type: 'cat', cSkin: '#000', cDark: '#333', cSuit: '#ffd700', pType: 'chi_blast', pColor: '#ffd700' },
    { id: 'fighterhawk', name: 'FIGHTER-HAWK', type: 'bird', cSkin: '#F8F8FF', cDark: '#006400', cSuit: '#F0E68C', pType: 'gun', pColor: '#F0FFFF', trait: 'fly' },
    { id: 'moon', name: 'MOON-OWL', type: 'bird', cSkin: '#FFF', cDark: '#EEE', cSuit: '#DDD', pType: 'boomerang', pColor: '#FFF', trait: 'fly' },
    { id: 'widow', name: 'BLACK WIDOW-PUG', type: 'dog_flat', cSkin: '#000', cDark: '#111', cSuit: '#222', pType: 'gun', pColor: '#00FFFF', trait: 'climb' },
    { id: 'minnowion', name: 'MINNOW-ION', type: 'fish', cSkin: '#ffd700', cDark: '#0000ff', cSuit: '#0000ff', pType: 'banana_gun', pColor: '#ffd700' },
    { id: 'mooana', name: 'MOO-ANA', type: 'cow', cSkin: '#cd853f', cDark: '#8b4513', cSuit: '#ff4500', pType: 'oar_smash', pColor: '#deb887' },
    { id: 'batmanatee', name: 'BAT-MANATEE', type: 'fish', cSkin: '#000', cDark: '#333', cSuit: '#111', pType: 'batarang', pColor: '#ffff00' },
    { id: 'moolan', name: 'MOO-LAN', type: 'cow', cSkin: '#ffe4c4', cDark: '#000', cSuit: '#ff69b4', pType: 'sword_slash', pColor: '#c0c0c0' },
    { id: 'yodog', name: 'YO-DOG', type: 'dog_pointy', cSkin: '#9acd32', cDark: '#fff', cSuit: '#f5deb3', pType: 'magic', pColor: '#00ff00' },
    { id: 'alihen', name: 'ALI-HEN', type: 'chicken', cSkin: '#000', cDark: '#111', cSuit: '#222', pType: 'acid_spit', pColor: '#00ff00', trait: 'climb' },
    { id: 'resortstone', name: 'RESORT-STONE', type: 'stone', cSkin: '#808080', cDark: '#FAFAD2', cSuit: '#8FBC8F', pType: 'boomerang', pColor: '#00FF7F' },
    { id: 'shang', name: 'SHANG-CHI-PANDA', type: 'bear', cSkin: '#000', cDark: '#FFF', cSuit: '#FF0000', pType: 'melee_smash', pColor: '#FFD700' },
    { id: 'detectivemonkey', name: 'DETECTIVE-MONKEY', type: 'monkey', cSkin: '#000080', cDark: '#F5F5F5', cSuit: '#F0FFFF', pType: 'laser', pColor: '#FAEBD7', trait: 'climb' },
    { id: 'defenderroof', name: 'DEFENDER-ROOF', type: 'stone', cSkin: '#A52A2A', cDark: '#0000FF', cSuit: '#000000', pType: 'boomerang', pColor: '#D2691E' },
    { id: 'drmanhatcat', name: 'DR MAN-CAT-TAN', type: 'cat', cSkin: '#00bfff', cDark: '#000', cSuit: '#00bfff', pType: 'atom_blast', pColor: '#fff', trait: 'fly' },
    { id: 'ninjakangaroo', name: 'NINJA-KANGAROO', type: 'rabbit', cSkin: '#DCDCDC', cDark: '#F0FFF0', cSuit: '#8FBC8F', pType: 'card_throw', pColor: '#808080', trait: 'climb' },
    { id: 'mutantkoala', name: 'MUTANT-KOALA', type: 'bear', cSkin: '#4682B4', cDark: '#DCDCDC', cSuit: '#008000', pType: 'laser', pColor: '#696969', trait: 'climb' },
    { id: 'policecroc', name: 'POLICE-CROC', type: 'croc', cSkin: '#228B22', cDark: '#006400', cSuit: '#A52A2A', pType: 'shuriken', pColor: '#A0522D' },
    { id: 'supermanta', name: 'SUPER-MANTA', type: 'fish', cSkin: '#0000ff', cDark: '#ff0000', cSuit: '#0000ff', pType: 'heat_vision', pColor: '#ff0000', trait: 'fly' },
    { id: 'freddycougar', name: 'FREDDY COUGAR', type: 'cat', cSkin: '#cd5c5c', cDark: '#8b0000', cSuit: '#006400', pType: 'claw_glove', pColor: '#c0c0c0' },
    { id: 'groot', name: 'GROOT-BARK', type: 'tree', cSkin: '#8B4513', cDark: '#A0522D', cSuit: '#654321', pType: 'melee_smash', pColor: '#8B4513' },
    { id: 'chewbarka', name: 'CHEW-BARK-A', type: 'dog_long', cSkin: '#8b4513', cDark: '#a0522d', cSuit: '#8b4513', pType: 'melee_smash', pColor: '#8b4513' },
    { id: 'eweve', name: 'EWE-VE', type: 'goat', cSkin: '#fff', cDark: '#000', cSuit: '#fff', pType: 'plasma_gun', pColor: '#0000ff', trait: 'fly' },
    { id: 'ogreguinea', name: 'OGRE-GUINEA', type: 'rodent', cSkin: '#FFE4C4', cDark: '#708090', cSuit: '#2F4F4F', pType: 'gun', pColor: '#00CED1' },
    { id: 'farmpig', name: 'FARM-PIG', type: 'pig', cSkin: '#696969', cDark: '#696969', cSuit: '#FFF5EE', pType: 'lightning', pColor: '#00FFFF' },
    { id: 'guardbrick', name: 'GUARD-BRICK', type: 'stone', cSkin: '#66CDAA', cDark: '#C0C0C0', cSuit: '#40E0D0', pType: 'shuriken', pColor: '#008B8B' },
    { id: 'wickedfish', name: 'WICKED FISH', type: 'fish', cSkin: '#00ff00', cDark: '#000', cSuit: '#000', pType: 'broom_splash', pColor: '#00ff00' },
    { id: 'beastbee', name: 'BEE-ST', type: 'bee', cSkin: '#8b4513', cDark: '#ffd700', cSuit: '#000080', pType: 'rose_petal', pColor: '#ff0000', trait: 'fly' },
    { id: 'wonderwombat', name: 'WONDER WOMBAT', type: 'rodent', cSkin: '#deb887', cDark: '#000', cSuit: '#ff0000', pType: 'lasso', pColor: '#ffd700' },
    { id: 'woodpecker', name: 'WOOD-Y PECKER', type: 'bird', cSkin: '#d2b48c', cDark: '#a52a2a', cSuit: '#ffff00', pType: 'pull_string', pColor: '#a52a2a', trait: 'fly' },
    { id: 'madcatter', name: 'MAD CAT-TER', type: 'cat', cSkin: '#dda0dd', cDark: '#800080', cSuit: '#008000', pType: 'tea_pot', pColor: '#da70d6' },
    { id: 'headsmanshark', name: 'HEADSMAN-SHARK', type: 'fish', cSkin: '#4682B4', cDark: '#00FF7F', cSuit: '#FFE4C4', pType: 'melee_slash', pColor: '#D3D3D3' },
    { id: 'knightsheep', name: 'KNIGHT-SHEEP', type: 'goat', cSkin: '#D2691E', cDark: '#B8860B', cSuit: '#F0FFF0', pType: 'acid_spit', pColor: '#000080' },
    { id: 'duckula', name: 'DUCK-ULA', type: 'duck', cSkin: '#fff', cDark: '#000', cSuit: '#000', pType: 'fangs', pColor: '#ff0000', trait: 'fly' },
    { id: 'killerdonkey', name: 'KILLER-DONKEY', type: 'horse', cSkin: '#7FFF00', cDark: '#F0FFFF', cSuit: '#FFFACD', pType: 'grenade', pColor: '#708090' },
    { id: 'dead', name: 'DEAD-POODLE', type: 'poodle', cSkin: '#FF0000', cDark: '#000', cSuit: '#333', pType: 'gun', pColor: '#FF0000' },
    { id: 'stitchostrich', name: 'OSTRICH STITCH', type: 'bird', cSkin: '#0000ff', cDark: '#add8e6', cSuit: '#ff4500', pType: 'plasma_blaster', pColor: '#00ff00' },
    { id: 'monkeysifu', name: 'MONK-EY', type: 'monkey', cSkin: '#8b4513', cDark: '#000', cSuit: '#daa520', pType: 'staff', pColor: '#8b4513', trait: 'climb' },
    { id: 'ghost', name: 'GHOST-GOAT', type: 'goat', cSkin: '#FFF', cDark: '#FF4500', cSuit: '#000', pType: 'melee_slash', pColor: '#FF4500' },
    { id: 'oompallama', name: 'OOMPA LLAMA', type: 'goat', cSkin: '#ffa500', cDark: '#008000', cSuit: '#fff', pType: 'cocoa_bean', pColor: '#8b4513' },
    { id: 'starlord', name: 'STAR-LORD-FOX', type: 'fox', cSkin: '#FF8C00', cDark: '#8B0000', cSuit: '#8B4513', pType: 'laser', pColor: '#FFFF00', trait: 'fly' },
    { id: 'hercowles', name: 'HER-COW-LES', type: 'cow', cSkin: '#deb887', cDark: '#ffd700', cSuit: '#b8860b', pType: 'super_strength', pColor: '#ffd700' },
    { id: 'cheshirerat', name: 'CHESHIRE RAT', type: 'rodent', cSkin: '#da70d6', cDark: '#800080', cSuit: '#da70d6', pType: 'grin_fade', pColor: '#da70d6' },
    { id: 'caferaven', name: 'CAFE-RAVEN', type: 'bird', cSkin: '#008B8B', cDark: '#90EE90', cSuit: '#90EE90', pType: 'rocket', pColor: '#FFA500', trait: 'fly' },
    { id: 'grub', name: 'GRU-B', type: 'rodent', cSkin: '#ffe4e1', cDark: '#000', cSuit: '#696969', pType: 'freeze_ray', pColor: '#add8e6' },
    { id: 'princemonster', name: 'PRINCE-MONSTER', type: 'alien', cSkin: '#000080', cDark: '#808000', cSuit: '#FFDEAD', pType: 'gun', pColor: '#FFDEAD' },
    { id: 'chefdeer', name: 'CHEF-DEER', type: 'goat', cSkin: '#800000', cDark: '#EEE8AA', cSuit: '#FFE4C4', pType: 'rocket', pColor: '#000080' },
    { id: 'lightningmcqueen', name: 'LIGHTNING MC-BEE', type: 'bee', cSkin: '#ff0000', cDark: '#ffd700', cSuit: '#ff0000', pType: 'speed_sting', pColor: '#ffff00', trait: 'fly' },
    { id: 'devilcastle', name: 'DEVIL-CASTLE', type: 'stone', cSkin: '#48D1CC', cDark: '#008000', cSuit: '#0000FF', pType: 'water_gun', pColor: '#7CFC00' },
    { id: 'indianabones', name: 'INDIANA BONES', type: 'dog_pointy', cSkin: '#deb887', cDark: '#8b4513', cSuit: '#d2b48c', pType: 'whip', pColor: '#8b4513', trait: 'climb' },
    { id: 'greensparrow', name: 'GREEN SPAR-ROW', type: 'bird', cSkin: '#006400', cDark: '#000', cSuit: '#228b22', pType: 'bow', pColor: '#00ff00', trait: 'fly' },
    { id: 'johnlick', name: 'JOHN LICK', type: 'dog_pointy', cSkin: '#000', cDark: '#fff', cSuit: '#000', pType: 'pencil', pColor: '#c0c0c0' },
    { id: 'fiony', name: 'FIO-NY', type: 'horse', cSkin: '#32cd32', cDark: '#006400', cSuit: '#006400', pType: 'karate_kick', pColor: '#32cd32' },
    { id: 'neot', name: 'NEO-T', type: 'lizard', cSkin: '#000', cDark: '#000', cSuit: '#000', pType: 'bullet_time', pColor: '#fff', trait: 'fly' },
    { id: 'tinkerbull', name: 'TINKER-BULL', type: 'cow', cSkin: '#ffe4c4', cDark: '#ffd700', cSuit: '#00ff00', pType: 'wand_sparkle', pColor: '#ffd700', trait: 'fly' },
    { id: 'directorreindeer', name: 'DIRECTOR-REINDEER', type: 'goat', cSkin: '#8FBC8F', cDark: '#A52A2A', cSuit: '#00FA9A', pType: 'gun', pColor: '#B0C4DE', trait: 'fly' },
    { id: 'snowcrow', name: 'CROW WHITE', type: 'bird', cSkin: '#000', cDark: '#ff0000', cSuit: '#0000ff', pType: 'apple_poison', pColor: '#ff0000', trait: 'fly' },
    { id: 'mooshu', name: 'MOO-SHU', type: 'lizard', cSkin: '#ff0000', cDark: '#ffd700', cSuit: '#ff0000', pType: 'fire_spit', pColor: '#ff4500' },
    { id: 'murdererforest', name: 'MURDERER-FOREST', type: 'tree', cSkin: '#006400', cDark: '#F8F8FF', cSuit: '#4682B4', pType: 'spread', pColor: '#008B8B' },
    { id: 'robbereagle', name: 'ROBBER-EAGLE', type: 'bird', cSkin: '#F8F8FF', cDark: '#4682B4', cSuit: '#3CB371', pType: 'lightning', pColor: '#20B2AA', trait: 'fly' },
    { id: 'frodobaggins', name: 'FRODO BAG-GINS', type: 'cat', cSkin: '#deb887', cDark: '#8b4513', cSuit: '#d2b48c', pType: 'sting', pColor: '#00bfff' },
    { id: 'cap', name: 'CAPTAIN EAGLE', type: 'bird', cSkin: '#FFF', cDark: '#A52A2A', cSuit: '#0000FF', pType: 'boomerang', pColor: '#FFF', trait: 'fly' },
    { id: 'docbrown', name: 'DOG BROWN', type: 'dog_long', cSkin: '#fff', cDark: '#ccc', cSuit: '#fff', pType: 'flux_capacitor', pColor: '#00ffff' },
    { id: 'buzzlightbear', name: 'BUZZ LIGHT-BEAR', type: 'bear', cSkin: '#fff', cDark: '#32cd32', cSuit: '#fff', pType: 'laser_wrist', pColor: '#ff0000', trait: 'fly' },
    { id: 'matear', name: 'MA-TEAR', type: 'dog_flat', cSkin: '#8b4513', cDark: '#2f4f4f', cSuit: '#8b4513', pType: 'tow_hook', pColor: '#8b4513' },
    { id: 'musicianturkey', name: 'MUSICIAN-TURKEY', type: 'duck', cSkin: '#228B22', cDark: '#DEB887', cSuit: '#FFFAF0', pType: 'spread', pColor: '#FF0000', trait: 'fly' },
    { id: 'doray', name: 'DO-RAY', type: 'fish', cSkin: '#4169e1', cDark: '#ffd700', cSuit: '#000', pType: 'memory_loss', pColor: '#4169e1' },
    { id: 'composerfrog', name: 'COMPOSER-FROG', type: 'frog', cSkin: '#32CD32', cDark: '#006400', cSuit: '#9ACD32', pType: 'boomerang', pColor: '#FFDEAD' },
    { id: 'totoad', name: 'TO-TOAD', type: 'frog', cSkin: '#000', cDark: '#333', cSuit: '#000', pType: 'lick', pColor: '#ff69b4' },
    { id: 'journalistceiling', name: 'JOURNALIST-CEILING', type: 'stone', cSkin: '#FFDAB9', cDark: '#A0522D', cSuit: '#228B22', pType: 'melee_slash', pColor: '#800000' },
    { id: 'invisibull', name: 'INVISI-BULL', type: 'cow', cSkin: 'rgba(255,255,255,0.5)', cDark: 'rgba(0,0,0,0.5)', cSuit: 'rgba(255,255,255,0.2)', pType: 'mystery', pColor: '#fff' },
    { id: 'trollpeacock', name: 'TROLL-PEACOCK', type: 'bird', cSkin: '#8FBC8F', cDark: '#40E0D0', cSuit: '#00FF7F', pType: 'gun', pColor: '#FFF5EE', trait: 'fly' },
    { id: 'professorkangaroo', name: 'PROFESSOR-KANGAROO', type: 'rabbit', cSkin: '#FFE4C4', cDark: '#C0C0C0', cSuit: '#000000', pType: 'spread', pColor: '#40E0D0' },
    { id: 'storestump', name: 'STORE-STUMP', type: 'tree', cSkin: '#006400', cDark: '#6495ED', cSuit: '#000000', pType: 'boomerang', pColor: '#FFDEAD' },
    { id: 'meowpheus', name: 'MEOW-PHEUS', type: 'cat', cSkin: '#222', cDark: '#000', cSuit: '#111', pType: 'katana', pColor: '#800080' },
    { id: 'greenlantern', name: 'GREEN LAN-TERN', type: 'bird', cSkin: '#000', cDark: '#00ff00', cSuit: '#006400', pType: 'construct', pColor: '#00ff00', trait: 'fly' },
    { id: 'lukeskydog', name: 'LUKE SKY-DOG', type: 'dog_pointy', cSkin: '#fff', cDark: '#d4a76a', cSuit: '#fff', pType: 'laser', pColor: '#00ff00' },
    { id: 'gollum', name: 'GOL-LAMB', type: 'goat', cSkin: '#ffe4e1', cDark: '#d2b48c', cSuit: '#ffe4e1', pType: 'rock_smash', pColor: '#808080', trait: 'climb' },
    { id: 'leatherfish', name: 'LEATHER-FISH', type: 'fish', cSkin: '#f4a460', cDark: '#8b4513', cSuit: '#deb887', pType: 'chainsaw', pColor: '#ffff00' },
    { id: 'wolvie', name: 'WOLVER-WEENIE', type: 'dog_long', cSkin: '#8B4513', cDark: '#000', cSuit: '#FFFF00', pType: 'melee_slash', pColor: '#C0C0C0' },
    { id: 'jasonboarhees', name: 'JASON BOAR-HEES', type: 'pig', cSkin: '#deb887', cDark: '#000', cSuit: '#000080', pType: 'machete', pColor: '#c0c0c0' },
    { id: 'aquamander', name: 'AQUA-MANDER', type: 'lizard', cSkin: '#ffd700', cDark: '#008000', cSuit: '#daa520', pType: 'trident', pColor: '#00bfff' },
    { id: 'owladdin', name: 'OWL-ADDIN', type: 'bird', cSkin: '#deb887', cDark: '#000', cSuit: '#fff', pType: 'lamp_rub', pColor: '#ffd700', trait: 'fly' },
    { id: 'winter', name: 'WINTER-WOLF', type: 'dog_pointy', cSkin: '#FFF', cDark: '#808080', cSuit: '#000', pType: 'gun', pColor: '#C0C0C0' },
    { id: 'zombiefish', name: 'ZOMBIE-FISH', type: 'fish', cSkin: '#F0F8FF', cDark: '#D2691E', cSuit: '#008000', pType: 'ice_beam', pColor: '#F0FFFF' },
    { id: 'scarecrow', name: 'SCARE-CROW', type: 'bird', cSkin: '#f5deb3', cDark: '#8b4513', cSuit: '#a0522d', pType: 'straw_burst', pColor: '#f5deb3', trait: 'fly' },
    { id: 'makeupgate', name: 'MAKEUP-GATE', type: 'stone', cSkin: '#FFDEAD', cDark: '#F0F8FF', cSuit: '#D2B48C', pType: 'fireball', pColor: '#008000' },
    { id: 'dogzilla', name: 'DOG-ZILLA', type: 'dog_flat', cSkin: '#2f4f4f', cDark: '#000', cSuit: '#2f4f4f', pType: 'atomic_breath', pColor: '#00bfff' },
    { id: 'catatouille', name: 'CAT-ATOUILLE', type: 'cat', cSkin: '#808080', cDark: '#ffc0cb', cSuit: '#fff', pType: 'spoon_whack', pColor: '#c0c0c0' },
    { id: 'predatoad', name: 'PREDA-TOAD', type: 'frog', cSkin: '#556b2f', cDark: '#8b4513', cSuit: '#a9a9a9', pType: 'plasma_caster', pColor: '#00ffff' },
    { id: 'nightllama', name: 'NIGHT-LLAMA', type: 'horse', cSkin: '#808000', cDark: '#008000', cSuit: '#FFFF00', pType: 'melee_smash', pColor: '#FFFF00' },
    { id: 'peterprawn', name: 'PETER PRAWN', type: 'lizard', cSkin: '#ff7f50', cDark: '#008000', cSuit: '#006400', pType: 'pixie_dust', pColor: '#ffd700', trait: 'fly' },
    { id: 'lyin', name: "LYIN'", type: 'lion', cSkin: '#deb887', cDark: '#8b4513', cSuit: '#deb887', pType: 'courage_roar', pColor: '#ffd700' },
    { id: 'sunpegasus', name: 'SUN-PEGASUS', type: 'horse', cSkin: '#BDB76B', cDark: '#FFFAFA', cSuit: '#008000', pType: 'lightning', pColor: '#0000CD', trait: 'fly' },
    { id: 'hawkeye', name: 'HAWK-HEDGEHOG', type: 'hedgehog', cSkin: '#D2B48C', cDark: '#8B4513', cSuit: '#800080', pType: 'grenade', pColor: '#DDD' },
    { id: 'arielbird', name: 'AIR-IEL', type: 'bird', cSkin: '#ffe4e1', cDark: '#ff0000', cSuit: '#00ced1', pType: 'fork_comb', pColor: '#c0c0c0', trait: 'fly' },
    { id: 'galaxygod', name: 'GALAXY-GOD', type: 'human', cSkin: '#F0F8FF', cDark: '#BDB76B', cSuit: '#DAA520', pType: 'shuriken', pColor: '#FAF0E6', trait: 'fly' },
    { id: 'homepumpkin', name: 'HOME-PUMPKIN', type: 'pumpkin', cSkin: '#FFA500', cDark: '#006400', cSuit: '#D3D3D3', pType: 'ice_beam', pColor: '#ADFF2F' },
    { id: 'falcon', name: 'FALCON-PIGEON', type: 'bird', cSkin: '#808080', cDark: '#696969', cSuit: '#FF0000', pType: 'gun', pColor: '#CCC', trait: 'fly' },
    { id: 'edwardscissorclaws', name: 'ED SCISSOR-CLAWS', type: 'lizard', cSkin: '#fff', cDark: '#000', cSuit: '#000', pType: 'scissor_snip', pColor: '#c0c0c0' },
    { id: 'ursulabear', name: 'URSULA BEAR', type: 'bear', cSkin: '#dda0dd', cDark: '#fff', cSuit: '#000', pType: 'ink_tentacle', pColor: '#800080' },
    { id: 'captainhaddock', name: 'CAPTAIN HADDOCK', type: 'fish', cSkin: '#4682b4', cDark: '#000', cSuit: '#ff0000', pType: 'hook_hand', pColor: '#c0c0c0' },
    { id: 'tarantula', name: 'TAR-ANTULA', type: 'lizard', cSkin: '#deb887', cDark: '#8b4513', cSuit: '#deb887', pType: 'vine_swing', pColor: '#006400', trait: 'climb' },
    { id: 'agentsniff', name: 'AGENT SNIFF', type: 'dog_pointy', cSkin: '#fff', cDark: '#000', cSuit: '#000', pType: 'pistol', pColor: '#fff' },
    { id: 'mumbee', name: 'MUM-BEE', type: 'bee', cSkin: '#f5f5dc', cDark: '#d2b48c', cSuit: '#f5f5dc', pType: 'wrap', pColor: '#fff', trait: 'fly' },
    { id: 'hospitalchipmunk', name: 'HOSPITAL-CHIPMUNK', type: 'rodent', cSkin: '#FFEFD5', cDark: '#FFFACD', cSuit: '#008B8B', pType: 'card_throw', pColor: '#5F9EA0', trait: 'climb' },
    { id: 'phoenixdemon', name: 'PHOENIX-DEMON', type: 'goat', cSkin: '#EEE8AA', cDark: '#7FFF00', cSuit: '#6B8E23', pType: 'grenade', pColor: '#FFE4C4', trait: 'fly' },
    { id: 'michaelmeowers', name: 'MICHAEL MEOW-ERS', type: 'cat', cSkin: '#fff', cDark: '#000', cSuit: '#000080', pType: 'knife', pColor: '#c0c0c0' },
    { id: 'pug', name: 'IRON MUTT', type: 'dog_flat', cSkin: '#f3cf98', cDark: '#3b302a', cSuit: '#b0c4de', pType: 'laser', pColor: '#a020f0' },
    { id: 'dogothy', name: 'DOG-OTHY', type: 'dog_flat', cSkin: '#deb887', cDark: '#8b4513', cSuit: '#87ceeb', pType: 'basket', pColor: '#deb887' },
    { id: 'spider', name: 'SPIDER-PIG', type: 'pig', cSkin: '#FFC0CB', cDark: '#FF69B4', cSuit: '#FF0000', pType: 'gun', pColor: '#FFF', trait: 'climb' },
    { id: 'innmud', name: 'INN-MUD', type: 'stone', cSkin: '#FAF0E6', cDark: '#008080', cSuit: '#C0C0C0', pType: 'card_throw', pColor: '#9ACD32' },
    { id: 'et', name: 'E.T. BEE', type: 'bee', cSkin: '#deb887', cDark: '#8b4513', cSuit: '#deb887', pType: 'finger_glow', pColor: '#ffd700', trait: 'fly' },
    { id: 'paintervillain', name: 'PAINTER-VILLAIN', type: 'human', cSkin: '#F0E68C', cDark: '#3CB371', cSuit: '#66CDAA', pType: 'laser', pColor: '#F0F8FF' },
    { id: 'hairyotter', name: 'HAIRY OTTER', type: 'rodent', cSkin: '#8b4513', cDark: '#000', cSuit: '#000', pType: 'magic_wand', pColor: '#ff0000' },
    { id: 'pinhead', name: 'PIN-HOG', type: 'pig', cSkin: '#fff', cDark: '#000', cSuit: '#000', pType: 'chain_hook', pColor: '#c0c0c0' },
    { id: 'scarlet', name: 'SCARLET-SKUNK', type: 'skunk', cSkin: '#000', cDark: '#FFF', cSuit: '#FF0000', pType: 'magic', pColor: '#FF0000' },
    { id: 'raccoon', name: 'CPT TRASH', type: 'raccoon', cSkin: '#888', cDark: '#444', cSuit: '#555', pType: 'boomerang', pColor: '#aaa' },
    { id: 'glinduck', name: 'GLIN-DUCK', type: 'duck', cSkin: '#ffe4e1', cDark: '#ff69b4', cSuit: '#ffc0cb', pType: 'bubble_wand', pColor: '#ffc0cb', trait: 'fly' },
    { id: 'aquariumforest', name: 'AQUARIUM-FOREST', type: 'tree', cSkin: '#FFFAFA', cDark: '#1E90FF', cSuit: '#556B2F', pType: 'laser', pColor: '#F5F5DC' },
    { id: 'drax', name: 'DRAX-BULLDOG', type: 'dog_flat', cSkin: '#008000', cDark: '#FF0000', cSuit: '#000080', pType: 'melee_slash', pColor: '#CCC' },
    { id: 'shadowpanda', name: 'SHADOW-PANDA', type: 'bear', cSkin: '#6495ED', cDark: '#008080', cSuit: '#808080', pType: 'melee_smash', pColor: '#F0F8FF' },
    { id: 'unicorncyborg', name: 'UNICORN-CYBORG', type: 'robot', cSkin: '#6495ED', cDark: '#FFEBCD', cSuit: '#2E8B57', pType: 'lightning', pColor: '#FFE4C4' },
    { id: 'rambo', name: 'RAM-BO', type: 'goat', cSkin: '#deb887', cDark: '#000', cSuit: '#2f4f4f', pType: 'machine_gun', pColor: '#ffd700' },
    { id: 'beetlegoose', name: 'BEETLE-GOOSE', type: 'duck', cSkin: '#fff', cDark: '#000', cSuit: '#000', pType: 'bug_spit', pColor: '#00ff00', trait: 'fly' },
    { id: 'princessleia', name: 'PRINCESS LAY-A', type: 'chicken', cSkin: '#fff', cDark: '#ccc', cSuit: '#fff', pType: 'laser', pColor: '#0000ff' },
    { id: 'spectrebison', name: 'SPECTRE-BISON', type: 'cow', cSkin: '#FFF0F5', cDark: '#FFFFF0', cSuit: '#9ACD32', pType: 'card_throw', pColor: '#FFDEAD' },
    { id: 'ghostfish', name: 'GHOST-FISH', type: 'fish', cSkin: '#fff', cDark: '#000', cSuit: '#000', pType: 'scream_mask', pColor: '#fff' },
    { id: 'darthvadehound', name: 'DARTH VADE-HOUND', type: 'dog_pointy', cSkin: '#000', cDark: '#111', cSuit: '#000', pType: 'laser', pColor: '#ff0000' },
    { id: 'eelsad', name: 'EEL-SA', type: 'fish', cSkin: '#add8e6', cDark: '#fff', cSuit: '#00bfff', pType: 'ice_palace', pColor: '#e0ffff' },
    { id: 'incrabible', name: 'MR IN-CRAB-IBLE', type: 'lizard', cSkin: '#ff0000', cDark: '#000', cSuit: '#ff0000', pType: 'claw_smash', pColor: '#ff0000' },
    { id: 'pennywise', name: 'HEN-NYWISE', type: 'chicken', cSkin: '#fff', cDark: '#ff0000', cSuit: '#c0c0c0', pType: 'balloon', pColor: '#ff0000' },
    { id: 'war', name: 'WAR-RHINO', type: 'rhino', cSkin: '#708090', cDark: '#2F4F4F', cSuit: '#000', pType: 'grenade', pColor: '#999' },
    { id: 'grinchfinch', name: 'GRINCH FINCH', type: 'bird', cSkin: '#32cd32', cDark: '#006400', cSuit: '#ff0000', pType: 'ornament_bomb', pColor: '#ff0000', trait: 'fly' },
    { id: 'pussinboats', name: 'PUSS IN BOATS', type: 'cat', cSkin: '#ffa500', cDark: '#000', cSuit: '#8b4513', pType: 'rapier', pColor: '#c0c0c0' },
    { id: 'hantoad', name: 'HAN TOAD-LO', type: 'frog', cSkin: '#556b2f', cDark: '#000', cSuit: '#000', pType: 'laser', pColor: '#ff0000' },
    { id: 'tinram', name: 'TIN RAM', type: 'goat', cSkin: '#c0c0c0', cDark: '#808080', cSuit: '#c0c0c0', pType: 'oil_can', pColor: '#000' },
    { id: 'rockybalboa', name: 'ROCKY BULL-BOA', type: 'snake', cSkin: '#8b4513', cDark: '#000', cSuit: '#000080', pType: 'boxing_glove', pColor: '#ff0000' },
    { id: 'professorskunk', name: 'PROFESSOR-SKUNK', type: 'skunk', cSkin: '#F4A460', cDark: '#800000', cSuit: '#2F4F4F', pType: 'rocket', pColor: '#800000' },
    { id: 'sparock', name: 'SPA-ROCK', type: 'stone', cSkin: '#000000', cDark: '#DEB887', cSuit: '#000080', pType: 'lightning', pColor: '#0000FF' },
    { id: 'directordirt', name: 'DIRECTOR-DIRT', type: 'stone', cSkin: '#00FA9A', cDark: '#F5FFFA', cSuit: '#FFFAFA', pType: 'spread', pColor: '#008080' },
    { id: 'factoryskeleton', name: 'FACTORY-SKELETON', type: 'skeleton', cSkin: '#FDF5E6', cDark: '#FFFACD', cSuit: '#556B2F', pType: 'acid_spit', pColor: '#F5F5F5' },
    { id: 'shehulk', name: 'SHE-HULK-HAMSTER', type: 'rodent', cSkin: '#32CD32', cDark: '#006400', cSuit: '#800080', pType: 'melee_smash', pColor: '#00FF00' },
    { id: 'whalee', name: 'WHAL-E', type: 'fish', cSkin: '#ffd700', cDark: '#808080', cSuit: '#ffd700', pType: 'trash_cube', pColor: '#8b4513' },
    { id: 'hanniball', name: 'HAM-NIBAL', type: 'pig', cSkin: '#ffc0cb', cDark: '#a52a2a', cSuit: '#fff', pType: 'mask_bite', pColor: '#a52a2a' },
    { id: 'aquaalpaca', name: 'AQUA-ALPACA', type: 'horse', cSkin: '#FFE4E1', cDark: '#FFDEAD', cSuit: '#F5DEB3', pType: 'rocket', pColor: '#FAFAD2' },
    { id: 'ant', name: 'ANT-EATER-MAN', type: 'anteater', cSkin: '#808080', cDark: '#404040', cSuit: '#FF0000', pType: 'melee_smash', pColor: '#FF0000', trait: 'climb' },
    { id: 'creaturehedgehog', name: 'CREATURE-HEDGEHOG', type: 'hedgehog', cSkin: '#00FF00', cDark: '#DAA520', cSuit: '#008B8B', pType: 'melee_smash', pColor: '#40E0D0' },
    { id: 'alienboulder', name: 'ALIEN-BOULDER', type: 'stone', cSkin: '#808080', cDark: '#FAEBD7', cSuit: '#006400', pType: 'ice_beam', pColor: '#00BFFF' },
    { id: 'gandalfthegreyhound', name: 'GANDALF GREY-HOUND', type: 'dog_long', cSkin: '#d3d3d3', cDark: '#a9a9a9', cSuit: '#808080', pType: 'staff_magic', pColor: '#fff' },
    { id: 'jamespond', name: 'JAMES POND', type: 'frog', cSkin: '#006400', cDark: '#000', cSuit: '#000', pType: 'silencer', pColor: '#c0c0c0' },
    { id: 'jafrog', name: 'JA-FROG', type: 'frog', cSkin: '#deb887', cDark: '#000', cSuit: '#000', pType: 'snake_staff', pColor: '#ffd700' },
    { id: 'rocket', name: 'ROCKET-RABBIT', type: 'rabbit', cSkin: '#A9A9A9', cDark: '#696969', cSuit: '#FF4500', pType: 'grenade', pColor: '#FF4500', trait: 'fly' },
    { id: 'simbasheep', name: 'SIM-BAA', type: 'goat', cSkin: '#ffd700', cDark: '#8b4513', cSuit: '#ffd700', pType: 'circle_life', pColor: '#ffd700' },
    { id: 'martymcfly', name: 'MARTY MC-FLY', type: 'bee', cSkin: '#daa520', cDark: '#000', cSuit: '#ff4500', pType: 'hoverboard', pColor: '#ff69b4', trait: 'fly' },
    { id: 'queenofharts', name: 'QUEEN OF HARTS', type: 'goat', cSkin: '#fff', cDark: '#ff0000', cSuit: '#000', pType: 'card_soldier', pColor: '#ff0000' },
    { id: 'shrewk', name: 'SHREW-K', type: 'rodent', cSkin: '#32cd32', cDark: '#556b2f', cSuit: '#f5f5dc', pType: 'onion_gas', pColor: '#32cd32' },
    { id: 'quick', name: 'QUICK-CHEETAH', type: 'cat', cSkin: '#D3D3D3', cDark: '#A9A9A9', cSuit: '#87CEEB', pType: 'melee_slash', pColor: '#87CEEB' },
    { id: 'darklog', name: 'DARK-LOG', type: 'tree', cSkin: '#F0E68C', cDark: '#00FFFF', cSuit: '#00CED1', pType: 'water_gun', pColor: '#FFFFFF' },
    { id: 'mrtomatohead', name: 'MR TOMATO HEAD', type: 'pumpkin', cSkin: '#ff0000', cDark: '#000', cSuit: '#0000ff', pType: 'parts_throw', pColor: '#fff' },
    { id: 'alienlion', name: 'ALIEN-LION', type: 'cat', cSkin: '#87CEFA', cDark: '#008B8B', cSuit: '#708090', pType: 'melee_slash', pColor: '#00FF00' },
    { id: 'vision', name: 'VISION-ZEBRA', type: 'horse', cSkin: '#FFC0CB', cDark: '#008000', cSuit: '#FFFF00', pType: 'laser', pColor: '#FFFF00', trait: 'fly' },
    { id: 'shopstone', name: 'SHOP-STONE', type: 'stone', cSkin: '#F0FFFF', cDark: '#A0522D', cSuit: '#FFEFD5', pType: 'fireball', pColor: '#E6E6FA' },
    { id: 'chucky', name: 'CLUCK-Y', type: 'chicken', cSkin: '#ffe4c4', cDark: '#ff4500', cSuit: '#0000ff', pType: 'knife_doll', pColor: '#c0c0c0' },
    { id: 'strange', name: 'DR STRANGE-CAT', type: 'cat', cSkin: '#444', cDark: '#222', cSuit: '#0000FF', pType: 'magic', pColor: '#FFA500' },
    { id: 'terminator', name: 'TERMIN-GATOR', type: 'croc', cSkin: '#2f4f4f', cDark: '#000', cSuit: '#000', pType: 'shotgun', pColor: '#ff0000' },
    { id: 'cyboar', name: 'CY-BOAR', type: 'pig', cSkin: '#c0c0c0', cDark: '#000', cSuit: '#808080', pType: 'cannon', pColor: '#00ffff' },
    { id: 'shalamb', name: 'SHA-LAMB', type: 'goat', cSkin: '#fff', cDark: '#ffd700', cSuit: '#ff0000', pType: 'lightning_shout', pColor: '#ffd700', trait: 'fly' },
    { id: 'dare', name: 'DAREDEVIL-DOG', type: 'dog_pointy', cSkin: '#B22222', cDark: '#800000', cSuit: '#FF0000', pType: 'melee_slash', pColor: '#FF0000' },
    { id: 'restaurantwolf', name: 'RESTAURANT-WOLF', type: 'wolf', cSkin: '#191970', cDark: '#FFE4C4', cSuit: '#B8860B', pType: 'ice_beam', pColor: '#E6E6FA' },
    { id: 'wraithhouse', name: 'WRAITH-HOUSE', type: 'stone', cSkin: '#800000', cDark: '#98FB98', cSuit: '#000080', pType: 'acid_spit', pColor: '#5F9EA0' },
    { id: 'ranchwombat', name: 'RANCH-WOMBAT', type: 'rodent', cSkin: '#708090', cDark: '#D3D3D3', cSuit: '#000080', pType: 'melee_slash', pColor: '#FFE4C4', trait: 'climb' },
    { id: 'owlaf', name: 'OWL-AF', type: 'bird', cSkin: '#fff', cDark: '#ff8c00', cSuit: '#fff', pType: 'snow_flurry', pColor: '#fff', trait: 'fly' },
    { id: 'genieguinea', name: 'GENIE-GUINEA', type: 'rodent', cSkin: '#00bfff', cDark: '#ffd700', cSuit: '#00bfff', pType: 'wish_grant', pColor: '#00bfff', trait: 'fly' },
    { id: 'flashfish', name: 'FLASH-FISH', type: 'fish', cSkin: '#ff0000', cDark: '#ffd700', cSuit: '#ff0000', pType: 'speed_bolt', pColor: '#ffd700' },
    { id: 'trinibee', name: 'TRINI-BEE', type: 'bee', cSkin: '#000', cDark: '#ffff00', cSuit: '#000', pType: 'dual_pistol', pColor: '#fff', trait: 'fly' },
    { id: 'bakerhamster', name: 'BAKER-HAMSTER', type: 'rodent', cSkin: '#808000', cDark: '#00FFFF', cSuit: '#2E8B57', pType: 'fireball', pColor: '#87CEEB' },
    { id: 'pup', name: 'UP-PUP', type: 'dog_pointy', cSkin: '#deb887', cDark: '#8b4513', cSuit: '#a0522d', pType: 'balloon_house', pColor: '#ff0000', trait: 'fly' },
    { id: 'ironmouse', name: 'IRON-MOUSE', type: 'rodent', cSkin: '#808080', cDark: '#404040', cSuit: '#FF0000', pType: 'laser', pColor: '#FFFF00', trait: 'fly' },
    { id: 'lordblob', name: 'LORD-BLOB', type: 'alien', cSkin: '#008B8B', cDark: '#F8F8FF', cSuit: '#F0E68C', pType: 'water_gun', pColor: '#800080' },
    { id: 'wolfclam', name: 'WOLF-CLAM', type: 'wolf', cSkin: '#8b4513', cDark: '#000', cSuit: '#8b4513', pType: 'pearl', pColor: '#fff' },
    { id: 'panther', name: 'BLACK PANTHER', type: 'cat', cSkin: '#111', cDark: '#000', cSuit: '#222', pType: 'melee_slash', pColor: '#800080', trait: 'climb' },
    { id: 'stylistearth', name: 'STYLIST-EARTH', type: 'stone', cSkin: '#006400', cDark: '#F0E68C', cSuit: '#00CED1', pType: 'card_throw', pColor: '#90EE90' },
    { id: 'mageslime', name: 'MAGE-SLIME', type: 'alien', cSkin: '#00FA9A', cDark: '#BDB76B', cSuit: '#8FBC8F', pType: 'melee_smash', pColor: '#008080' },
    { id: 'stormgrouper', name: 'STORM-GROUPER', type: 'fish', cSkin: '#fff', cDark: '#000', cSuit: '#fff', pType: 'laser', pColor: '#ff0000' },
    { id: 'hulk', name: 'HULK-POODLE', type: 'poodle', cSkin: '#00FF00', cDark: '#006400', cSuit: '#800080', pType: 'melee_smash', pColor: '#00FF00' },
    { id: 'frankenswine', name: 'FRANK-EN-SWINE', type: 'pig', cSkin: '#90ee90', cDark: '#000', cSuit: '#2f4f4f', pType: 'bolt_neck', pColor: '#c0c0c0' },
    { id: 'punish', name: 'PUNISHER-PENGUIN', type: 'bird', cSkin: '#000', cDark: '#FFF', cSuit: '#000', pType: 'spread', pColor: '#FFF' },
    { id: 'sulleyseal', name: 'SUL-LEY SEAL', type: 'fish', cSkin: '#00ced1', cDark: '#800080', cSuit: '#00ced1', pType: 'scare_roar', pColor: '#00ced1' },
    { id: 'firedonkey', name: 'FIRE-DONKEY', type: 'horse', cSkin: '#191970', cDark: '#800000', cSuit: '#2F4F4F', pType: 'water_gun', pColor: '#EEE8AA' },
    { id: 'spyboulder', name: 'SPY-BOULDER', type: 'stone', cSkin: '#7FFFD4', cDark: '#ADD8E6', cSuit: '#E6E6FA', pType: 'card_throw', pColor: '#98FB98' },
    { id: 'corgi', name: 'THOR-GI', type: 'dog_pointy', cSkin: '#E3C099', cDark: '#FFF', cSuit: '#333', pType: 'boomerang', pColor: '#00FFFF' },
    { id: 'vipear', name: 'VI-PEAR', type: 'snake', cSkin: '#32cd32', cDark: '#006400', cSuit: '#9acd32', pType: 'fang_strike', pColor: '#9acd32' },
    { id: 'cat', name: 'BAT CAT', type: 'cat', cSkin: '#222', cDark: '#000', cSuit: '#111', pType: 'boomerang', pColor: '#ff69b4', trait: 'climb' },
    { id: 'jacksparrow', name: 'JACK SPAR-ROW', type: 'bird', cSkin: '#8b4513', cDark: '#000', cSuit: '#a52a2a', pType: 'flintlock', pColor: '#c0c0c0', trait: 'fly' },
    { id: 'nemoo', name: 'NE-MOO', type: 'cow', cSkin: '#ffa500', cDark: '#fff', cSuit: '#ffa500', pType: 'bubble_stream', pColor: '#add8e6' },
    { id: 'bobaferret', name: 'BOBA FERRET', type: 'rodent', cSkin: '#556b2f', cDark: '#2f4f4f', cSuit: '#808080', pType: 'rocket', pColor: '#00ff00', trait: 'fly' },
    { id: 'homelizard', name: 'HOME-LIZARD', type: 'lizard', cSkin: '#808000', cDark: '#CD853F', cSuit: '#BC8F8F', pType: 'melee_slash', pColor: '#FFF8DC', trait: 'climb' },
    { id: 'nunturtle', name: 'NUN-TURTLE', type: 'turtle', cSkin: '#2E8B57', cDark: '#006400', cSuit: '#FFFAFA', pType: 'melee_slash', pColor: '#FFE4E1' },
    { id: 'jocurr', name: 'JO-CURR', type: 'dog_pointy', cSkin: '#fff', cDark: '#00ff00', cSuit: '#800080', pType: 'gas', pColor: '#00ff00' },
    { id: 'eternal', name: 'ETERNAL-ELEPHANT', type: 'elephant', cSkin: '#808080', cDark: '#696969', cSuit: '#FFD700', pType: 'magic', pColor: '#FFD700' },
    { id: 'artistalien', name: 'ARTIST-ALIEN', type: 'alien', cSkin: '#FFEBCD', cDark: '#ADFF2F', cSuit: '#0000CD', pType: 'ice_beam', pColor: '#F5F5F5' },
    { id: 'polarbear', name: 'PO-LAR BEAR', type: 'bear', cSkin: '#fff', cDark: '#000', cSuit: '#d2b48c', pType: 'noodle_bowl', pColor: '#ffd700' },
    { id: 'frozonefrog', name: 'FRO-ZONE FROG', type: 'frog', cSkin: '#00bfff', cDark: '#fff', cSuit: '#00bfff', pType: 'ice_slide', pColor: '#e0ffff' },
    { id: 'forrestgrump', name: 'FORREST GRUMP', type: 'bear', cSkin: '#8b4513', cDark: '#000', cSuit: '#add8e6', pType: 'chocolate_box', pColor: '#8b4513' },
    { id: 'convictchicken', name: 'CONVICT-CHICKEN', type: 'duck', cSkin: '#D2691E', cDark: '#FFEBCD', cSuit: '#808080', pType: 'grenade', pColor: '#FFFF00', trait: 'fly' },
    { id: 'oozecrow', name: 'OOZE-CROW', type: 'bird', cSkin: '#ADD8E6', cDark: '#228B22', cSuit: '#778899', pType: 'lightning', pColor: '#9ACD32', trait: 'fly' },
    { id: 'paramedicpeacock', name: 'PARAMEDIC-PEACOCK', type: 'bird', cSkin: '#00FF00', cDark: '#FFF0F5', cSuit: '#0000FF', pType: 'laser', pColor: '#FDF5E6', trait: 'fly' },
    { id: 'skeletonram', name: 'SKELETON-RAM', type: 'goat', cSkin: '#006400', cDark: '#800080', cSuit: '#00FA9A', pType: 'gun', pColor: '#B0C4DE' },
    { id: 'mikewacowski', name: 'MIKE WA-COW-SKI', type: 'cow', cSkin: '#32cd32', cDark: '#fff', cSuit: '#32cd32', pType: 'eye_beam', pColor: '#32cd32' },
    { id: 'rex', name: 'REX-DOG', type: 'dog_pointy', cSkin: '#32cd32', cDark: '#006400', cSuit: '#32cd32', pType: 'tail_whip', pColor: '#32cd32' },
    { id: 'gamora', name: 'GAMORA-GECKO', type: 'lizard', cSkin: '#00FF00', cDark: '#006400', cSuit: '#000', pType: 'melee_slash', pColor: '#00FF00', trait: 'climb' },
    { id: 'roarschach', name: 'ROAR-SCHACH', type: 'lion', cSkin: '#deb887', cDark: '#000', cSuit: '#8b4513', pType: 'ink_blot', pColor: '#000' }
];
